import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { and, desc, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import {
  agentEvents,
  approvals,
  dataAssets,
  findingPolicies,
  findings,
  policyDocuments,
  remediationActions,
  users,
  type AgentEvent,
  type DataAsset,
  type Finding,
  type InsertUser,
  type PolicyDocument,
} from "../drizzle/schema";
import { ENV } from "./_core/env";

type MemoryApproval = { id: number; findingId: number; decision: "approved" | "rejected"; action: "redact" | "revoke_access"; note: string | null; approvedBy: number | null; createdAt: Date };
type MemoryLink = { id: number; findingId: number; policyId: number; relevance: number };

const memory = {
  nextId: 1,
  policies: [] as PolicyDocument[],
  assets: [] as DataAsset[],
  findings: [] as Finding[],
  links: [] as MemoryLink[],
  approvals: [] as MemoryApproval[],
  events: [] as AgentEvent[],
};

function nextId() { return memory.nextId++; }
function now() { return new Date(); }

function dashboardFrom(store: { assets: DataAsset[]; findings: Finding[]; approvals: MemoryApproval[]; events: AgentEvent[]; policies: PolicyDocument[]; links: MemoryLink[] }) {
  const assetMap = new Map(store.assets.map(asset => [asset.id, asset]));
  const enrichedFindings = [...store.findings].sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime()).map(finding => ({ ...finding, source: assetMap.get(finding.assetId)?.source ?? "OneDrive", assetName: assetMap.get(finding.assetId)?.name ?? "Unknown asset" }));
  const policyMap = Object.fromEntries(store.findings.map(finding => [finding.id, store.links.filter(link => link.findingId === finding.id).map(link => store.policies.find(policy => policy.id === link.policyId)).filter(Boolean)]));
  return {
    assets: [...store.assets].sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime()),
    findings: enrichedFindings,
    approvals: [...store.approvals].sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime()),
    events: [...store.events].sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime()).slice(0, 80),
    policies: store.policies,
    policyMap,
  };
}

let _sql: ReturnType<typeof postgres> | null = null;
let _db: ReturnType<typeof drizzle> | null = null;
let _schemaReady = false;

const TABLE_DDL = [
  `CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "openId" VARCHAR(64) NOT NULL UNIQUE,
    name TEXT,
    email VARCHAR(320),
    "loginMethod" VARCHAR(64),
    role VARCHAR(16) NOT NULL DEFAULT 'user',
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "lastSignedIn" TIMESTAMPTZ NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS data_assets (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    source VARCHAR(32) NOT NULL,
    content TEXT NOT NULL,
    "contentHash" VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS policy_documents (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    framework VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    citation VARCHAR(255) NOT NULL,
    excerpt TEXT NOT NULL,
    keywords TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS findings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "assetId" INT NOT NULL,
    severity VARCHAR(16) NOT NULL,
    "piiTypes" TEXT NOT NULL,
    evidence TEXT NOT NULL,
    summary TEXT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'open',
    recurrence INT NOT NULL DEFAULT 0,
    "priorFindingId" INT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS finding_policies (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "findingId" INT NOT NULL,
    "policyId" INT NOT NULL,
    relevance INT NOT NULL DEFAULT 0
  )`,
  `CREATE TABLE IF NOT EXISTS approvals (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "findingId" INT NOT NULL,
    decision VARCHAR(16) NOT NULL,
    action VARCHAR(32) NOT NULL,
    note TEXT,
    "approvedBy" INT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS remediation_actions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "findingId" INT NOT NULL,
    action VARCHAR(32) NOT NULL,
    "beforeHash" VARCHAR(128) NOT NULL,
    "afterHash" VARCHAR(128) NOT NULL,
    result TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS agent_events (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "eventType" VARCHAR(80) NOT NULL,
    "findingId" INT,
    "assetId" INT,
    payload TEXT NOT NULL,
    "previousHash" VARCHAR(128) NOT NULL,
    "eventHash" VARCHAR(128) NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
  )`,
];

function sslOption() {
  const caPath = `${homedir()}/.postgresql/root.crt`;
  if (existsSync(caPath)) {
    return { rejectUnauthorized: true, ca: readFileSync(caPath).toString() };
  }
  return "require" as const;
}

async function ensureSchema(sql: ReturnType<typeof postgres>) {
  if (_schemaReady) return;
  for (const statement of TABLE_DDL) {
    await sql.unsafe(statement);
  }
  _schemaReady = true;
}

export async function getDb() {
  if (_db) return _db;
  const url = process.env.DATABASE_URL;
  if (!url || !url.startsWith("postgres")) {
    if (url) console.warn("[Database] DATABASE_URL must be a postgres:// or postgresql:// CockroachDB connection string");
    return null;
  }
  try {
    _sql = postgres(url, { ssl: sslOption(), max: 4, idle_timeout: 20, connect_timeout: 15, onnotice: () => {} });
    await _sql`SELECT 1`;
    await ensureSchema(_sql);
    _db = drizzle(_sql);
    console.log("[Database] Connected to CockroachDB");
  } catch (error) {
    console.warn("[Database] Failed to connect:", error instanceof Error ? error.message : error);
    await _sql?.end({ timeout: 0 }).catch(() => undefined);
    _sql = null;
    _db = null;
  }
  return _db;
}

export function sha256(value: string) { return createHash("sha256").update(value).digest("hex"); }
export function computeEventHash(previousHash: string, eventType: string, findingId: number | undefined, assetId: number | undefined, payload: string) { return sha256([previousHash, eventType, findingId ?? '', assetId ?? '', payload].join('|')); }
export function requireApprovedAction(approved: boolean) { if (!approved) throw new Error('Approval required before destructive action'); }

export async function upsertUser(user: InsertUser): Promise<void> {
  if (!user.openId) throw new Error("User openId is required for upsert");
  const db = await getDb(); if (!db) return;
  const values: InsertUser = { openId: user.openId };
  const updateSet: Record<string, unknown> = {};
  (['name', 'email', 'loginMethod'] as const).forEach(field => { if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = values[field]; } });
  values.lastSignedIn = user.lastSignedIn ?? new Date(); updateSet.lastSignedIn = values.lastSignedIn;
  if (user.role) { values.role = user.role; updateSet.role = user.role; }
  else if (user.openId === ENV.ownerOpenId) { values.role = 'admin'; updateSet.role = 'admin'; }
  await db.insert(users).values(values).onConflictDoUpdate({ target: users.openId, set: updateSet });
}

export async function getUserByOpenId(openId: string) {
  const db = await getDb(); if (!db) return undefined;
  const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0];
}

const POLICY_SEEDS = [
  { framework: 'ICRC' as const, title: 'ICRC Professional Standards for Protection Work', citation: 'ICRC Professional Standards, data protection and confidentiality', excerpt: 'Personal data collected for protection work must be processed lawfully, securely, confidentially, and only for specified humanitarian purposes. Access should be limited to those who need it.', keywords: 'confidentiality, protection, humanitarian, access, purpose limitation, sensitive data' },
  { framework: 'GDPR' as const, title: 'GDPR Article 5 Principles', citation: 'GDPR Art. 5(1)(c)-(f)', excerpt: 'Personal data must be adequate, relevant and limited to what is necessary; accurate; kept no longer than necessary; and processed with integrity and confidentiality using appropriate security.', keywords: 'data minimisation, retention, integrity, confidentiality, security, personal data' },
  { framework: 'GDPR' as const, title: 'GDPR Article 32 Security of Processing', citation: 'GDPR Art. 32', excerpt: 'Controllers and processors must implement appropriate technical and organisational measures, including encryption, resilience, restoration, and regular testing of security controls.', keywords: 'security, encryption, resilience, access control, breach, processing' },
  { framework: 'Sphere Standards' as const, title: 'Sphere Humanitarian Protection Principles', citation: 'Sphere Handbook, Protection Principle 1', excerpt: 'Humanitarian actors should avoid exposing people to further harm and should protect people from physical and psychological harm, including risks created by information handling.', keywords: 'do no harm, protection, dignity, risk, humanitarian, affected people' },
  { framework: 'Sphere Standards' as const, title: 'Sphere Core Humanitarian Standard', citation: 'Sphere Handbook, CHS Commitment 4', excerpt: 'People affected by crisis have access to safe, responsive mechanisms for handling data, feedback, complaints, and sensitive information with respect and confidentiality.', keywords: 'accountability, confidentiality, feedback, sensitive information, affected people' },
];

export async function ensurePolicies() {
  const db = await getDb();
  if (!db) {
    if (memory.policies.length) return;
    memory.policies = POLICY_SEEDS.map(seed => ({ id: nextId(), createdAt: now(), ...seed }));
    return;
  }
  const existing = await db.select({ id: policyDocuments.id }).from(policyDocuments).limit(1); if (existing.length) return;
  await db.insert(policyDocuments).values(POLICY_SEEDS);
}

export async function listPolicies() {
  await ensurePolicies();
  const db = await getDb();
  if (!db) return memory.policies;
  return db.select().from(policyDocuments);
}

export async function getDashboardData() {
  await ensurePolicies();
  const db = await getDb();
  if (!db) return dashboardFrom(memory);
  const [assets, findingRows, approvalRows, events, policies, links] = await Promise.all([
    db.select().from(dataAssets).orderBy(desc(dataAssets.createdAt)),
    db.select().from(findings).orderBy(desc(findings.createdAt)),
    db.select().from(approvals).orderBy(desc(approvals.createdAt)),
    db.select().from(agentEvents).orderBy(desc(agentEvents.createdAt)).limit(80),
    db.select().from(policyDocuments),
    db.select().from(findingPolicies),
  ]);
  return dashboardFrom({ assets, findings: findingRows, approvals: approvalRows, events, policies, links });
}

export async function appendEvent(input: { eventType: string; findingId?: number; assetId?: number; payload: unknown }) {
  const payload = JSON.stringify(input.payload);
  const db = await getDb();
  if (!db) {
    const previousHash = memory.events.at(-1)?.eventHash ?? "GENESIS";
    const eventHash = computeEventHash(previousHash, input.eventType, input.findingId, input.assetId, payload);
    const event: AgentEvent = { id: nextId(), eventType: input.eventType, findingId: input.findingId ?? null, assetId: input.assetId ?? null, payload, previousHash, eventHash, createdAt: now() };
    memory.events.push(event);
    return { id: event.id, eventHash, previousHash };
  }
  const prior = await db.select().from(agentEvents).orderBy(desc(agentEvents.id)).limit(1);
  const previousHash = prior[0]?.eventHash ?? "GENESIS";
  const eventHash = computeEventHash(previousHash, input.eventType, input.findingId, input.assetId, payload);
  const [event] = await db.insert(agentEvents).values({ eventType: input.eventType, findingId: input.findingId, assetId: input.assetId, payload, previousHash, eventHash }).returning({ id: agentEvents.id });
  return { id: event.id, eventHash, previousHash };
}

export async function findPriorRemediated(assetHash: string) {
  const db = await getDb();
  if (!db) {
    const asset = [...memory.assets].reverse().find(item => item.contentHash === assetHash && item.status === "remediated");
    if (!asset) return undefined;
    return [...memory.findings].reverse().find(item => item.assetId === asset.id && item.status === "remediated");
  }
  const asset = await db.select().from(dataAssets).where(and(eq(dataAssets.contentHash, assetHash), eq(dataAssets.status, "remediated"))).orderBy(desc(dataAssets.createdAt)).limit(1);
  if (!asset[0]) return undefined;
  const prior = await db.select().from(findings).where(and(eq(findings.assetId, asset[0].id), eq(findings.status, "remediated"))).orderBy(desc(findings.createdAt)).limit(1);
  return prior[0];
}

export async function saveScan(input: { name: string; source: "OneDrive" | "Slack" | "Outlook"; content: string; contentHash: string; severity: "low" | "medium" | "high" | "critical"; piiTypes: string[]; evidence: string[]; summary: string; priorFindingId?: number; recurrence: number; policyIds: number[] }) {
  const db = await getDb();
  if (!db) {
    const createdAt = now();
    const asset: DataAsset = { id: nextId(), name: input.name, source: input.source, content: input.content, contentHash: input.contentHash, status: "active", createdAt, updatedAt: createdAt };
    const finding: Finding = { id: nextId(), assetId: asset.id, severity: input.severity, piiTypes: JSON.stringify(input.piiTypes), evidence: JSON.stringify(input.evidence), summary: input.summary, status: "open", recurrence: input.recurrence, priorFindingId: input.priorFindingId ?? null, createdAt, updatedAt: createdAt };
    memory.assets.push(asset);
    memory.findings.push(finding);
    input.policyIds.forEach(policyId => memory.links.push({ id: nextId(), findingId: finding.id, policyId, relevance: 100 }));
    await appendEvent({ eventType: "scan.completed", assetId: asset.id, findingId: finding.id, payload: { name: input.name, source: input.source, piiTypes: input.piiTypes, recurrence: input.recurrence } });
    return { assetId: asset.id, findingId: finding.id };
  }
  const [asset] = await db.insert(dataAssets).values({ name: input.name, source: input.source, content: input.content, contentHash: input.contentHash }).returning({ id: dataAssets.id });
  const assetId = asset.id;
  const [finding] = await db.insert(findings).values({ assetId, severity: input.severity, piiTypes: JSON.stringify(input.piiTypes), evidence: JSON.stringify(input.evidence), summary: input.summary, recurrence: input.recurrence, priorFindingId: input.priorFindingId }).returning({ id: findings.id });
  const findingId = finding.id;
  if (input.policyIds.length) await db.insert(findingPolicies).values(input.policyIds.map(policyId => ({ findingId, policyId, relevance: 100 })));
  await appendEvent({ eventType: "scan.completed", assetId, findingId, payload: { name: input.name, source: input.source, piiTypes: input.piiTypes, recurrence: input.recurrence } });
  return { assetId, findingId };
}

export async function approveFinding(findingId: number, action: "redact" | "revoke_access", approvedBy?: number, note?: string) {
  const db = await getDb();
  if (!db) {
    const finding = memory.findings.find(item => item.id === findingId);
    if (!finding) throw new Error("Finding not found");
    memory.approvals.push({ id: nextId(), findingId, action, decision: "approved", approvedBy: approvedBy ?? null, note: note ?? null, createdAt: now() });
    finding.status = "approved";
    finding.updatedAt = now();
    await appendEvent({ eventType: "approval.granted", findingId, payload: { action, note } });
    return;
  }
  await db.insert(approvals).values({ findingId, action, decision: "approved", approvedBy, note });
  await db.update(findings).set({ status: "approved" }).where(eq(findings.id, findingId));
  await appendEvent({ eventType: "approval.granted", findingId, payload: { action, note } });
}

export async function remediateFinding(findingId: number, action: "redact" | "revoke_access") {
  const redact = (content: string) => content.replace(/\b[A-Z][a-z]+\s[A-Z][a-z]+\b/g, "[REDACTED NAME]").replace(/\b(?:CASE|case)[-_ ]?\d{3,}\b/g, "[REDACTED CASE]").replace(/\b-?\d{1,3}\.\d{3,},\s*-?\d{1,3}\.\d{3,}\b/g, "[REDACTED GPS]").replace(/\b(?:diabetes|HIV|malaria|pregnant|medical)\b/gi, "[REDACTED MEDICAL]");
  const db = await getDb();
  if (!db) {
    const finding = memory.findings.find(item => item.id === findingId);
    if (!finding) throw new Error("Finding not found");
    requireApprovedAction(memory.approvals.some(item => item.findingId === findingId && item.decision === "approved" && item.action === action));
    const asset = memory.assets.find(item => item.id === finding.assetId);
    if (!asset) throw new Error("Asset not found");
    const beforeHash = sha256(asset.content);
    const afterContent = action === "redact" ? redact(asset.content) : `${asset.content}\n[ACCESS REVOKED]`;
    const afterHash = sha256(afterContent);
    asset.content = afterContent;
    asset.status = "remediated";
    asset.updatedAt = now();
    finding.status = "remediated";
    finding.updatedAt = now();
    await appendEvent({ eventType: "remediation.completed", findingId, assetId: asset.id, payload: { action, beforeHash, afterHash } });
    return { action, beforeHash, afterHash, content: afterContent };
  }
  const finding = (await db.select().from(findings).where(eq(findings.id, findingId)).limit(1))[0]; if (!finding) throw new Error("Finding not found");
  const approved = await db.select().from(approvals).where(and(eq(approvals.findingId, findingId), eq(approvals.decision, "approved"), eq(approvals.action, action))).limit(1);
  requireApprovedAction(Boolean(approved[0]));
  const asset = (await db.select().from(dataAssets).where(eq(dataAssets.id, finding.assetId)).limit(1))[0]; if (!asset) throw new Error("Asset not found");
  const beforeHash = sha256(asset.content);
  const afterContent = action === "redact" ? redact(asset.content) : `${asset.content}\n[ACCESS REVOKED]`;
  const afterHash = sha256(afterContent);
  await db.update(dataAssets).set({ content: afterContent, status: "remediated" }).where(eq(dataAssets.id, asset.id));
  await db.insert(remediationActions).values({ findingId, action, beforeHash, afterHash, result: action === "redact" ? "PII tokens redacted from stored content" : "Sharing marked as revoked" });
  await db.update(findings).set({ status: "remediated" }).where(eq(findings.id, findingId));
  await appendEvent({ eventType: "remediation.completed", findingId, assetId: asset.id, payload: { action, beforeHash, afterHash } });
  return { action, beforeHash, afterHash, content: afterContent };
}
